keys:
  - &yk-5-nfc age1yubikey1qg4gcageg0xhm0dt920qkth72mql7f2fmjv80xrguyhgzdpg8sw3zv7vaqm
  - &yk-5c-nano age1yubikey1qd3xwagpxplcjq6c5wsjzyfynx6p93n6a2c6z3jt22l7zk85ntyfuatmfq6
  - &desktop age1fhpkmpywlernhej78dvywqwu2ngtte9u7yx0lk9lxj3krqwerpuqy3mvw4
  - &desktop_hm age14gqtkkews0ttelvsuy0dky33q67jrv3vtyluun4te2zmymzp3uxs9qu4yt
  - &pi5-server age13sgj756jngug94tf3gcnjg79dsqcqm08x3tgrzphp2wj8gcd2ppqq3vucp
creation_rules:
  - path_regex: secrets/common\.ya?ml$
    key_groups:
      - age:
          - *yk-5-nfc
          - *yk-5c-nano
          - *desktop
          - *desktop_hm
          - *pi5-server
  - path_regex: secrets/desktop\.ya?ml$
    key_groups:
      - age:
          - *yk-5-nfc
          - *yk-5c-nano
          - *desktop
          - *desktop_hm
  - path_regex: secrets/pi5-server\.ya?ml$
    key_groups:
      - age:
          - *yk-5-nfc
          - *yk-5c-nano
          - *pi5-server
